=== Jorge-Puente-Garcia/Sew-4/XML/todo/circuito.dtd
<!ELEMENT circuito (tramo+)>
<!ELEMENT tramo (distanciaTramo, coordenada, numeroSector)>
<!ELEMENT distanciaTramo EMPTY>
<!ELEMENT coordenada EMPTY>
<!ELEMENT numeroSector (#PCDATA)>

<!ELEMENT circuitoInfo (nombre,longitudCircuito,anchuraMedia,
fechaCarrera, horaInicioEspañola, numeroVueltas, localidad,
pais, referecias ,fotografias,videos, circuito)>

<!ELEMENT referecias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT fotografias (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT videos (video*)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT unidadesCircuito (#PCDATA)>
<!ELEMENT longitudCircuito (valorLongitudCircuito,unidadesLongitudCircuito)>
<!ELEMENT unidadesLongitudCircuito (#PCDATA)>
<!ELEMENT valorLongitudCircuito (#PCDATA)>
<!ELEMENT anchuraMedia (valorAnchuraMedia,unidadesAnchuraMedia)>
<!ELEMENT unidadesAnchuraMedia (#PCDATA)>
<!ELEMENT valorAnchuraMedia (#PCDATA)>
<!ELEMENT fechaCarrera (#PCDATA)>
<!ELEMENT numeroVueltas (#PCDATA)>
<!ELEMENT horaInicioEspañola (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>

<!ATTLIST coordenada
    longitud CDATA #REQUIRED
    latitud CDATA #REQUIRED
    altitud CDATA #REQUIRED   
>
<!ATTLIST distanciaTramo 
    distancia CDATA #REQUIRED
    unidades CDATA #REQUIRED
>

=== Jorge-Puente-Garcia/Sew-4/XML/todo/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE circuitoInfo SYSTEM "circuito.dtd">

<circuitoInfo>
    <nombre>Circuito de Hungria</nombre>
    <longitudCircuito >
        <valorLongitudCircuito>4.381</valorLongitudCircuito>
        <unidadesLongitudCircuito>Km</unidadesLongitudCircuito>
    </longitudCircuito>
    <anchuraMedia >
        <valorAnchuraMedia>12</valorAnchuraMedia>
        <unidadesAnchuraMedia>m</unidadesAnchuraMedia>
    </anchuraMedia>
    <fechaCarrera>21/7/2024</fechaCarrera>
    <horaInicioEspañola>15:00</horaInicioEspañola>
    <numeroVueltas>70</numeroVueltas>
    <localidad>Mogyoród</localidad>
    <pais>Hungria</pais>
    <referecias>
        <referencia>https://es.motorsport.com/f1/news/horarios-hungria-como-ver-formula1/10634394/#:~:text=El%20circuito%20de%20Hungaroring%20est%C3%A1,kil%C3%B3metros%20Budapest%2C%20capital%20de%20Hungr%C3%ADa.</referencia>
        <referencia>https://www.caranddriver.com/es/formula-1/gran-premio/a46262726/gp-hungria-f1-2024/</referencia>
        <referencia>https://es.wikipedia.org/wiki/Gran_Premio_de_Hungr%C3%ADa</referencia>
    </referecias>
    <fotografias>
        <foto>Panorama.jpg </foto>
        <foto>RectaMeta.jpg </foto>
    </fotografias>
    <videos>
        <video>video.mp4</video>
    </videos>
    
    <circuito>
        <tramo> 
            <distanciaTramo distancia="557.11" unidades="metros"/>
            <coordenada longitud="47.579080" latitud="19.248078" altitud="236"/>
            <numeroSector>1</numeroSector>
        </tramo>

        <tramo>
            <distanciaTramo distancia="39.35" unidades="metros"/>
            <coordenada longitud="47.582244" latitud="19.242319" altitud="228"/>
            <numeroSector>1</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="132.50 " unidades="metros"/>
            <coordenada longitud="47.582510" latitud="19.242665" altitud="227"/>
            <numeroSector>1</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="286.63" unidades="metros"/>
            <coordenada longitud="47.582400" latitud="19.244424" altitud="226"/>
            <numeroSector>1</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="63.20" unidades="metros"/>
            <coordenada longitud="47.580902" latitud="19.247534" altitud="220"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="56.08" unidades="metros"/>
            <coordenada longitud="47.580924" latitud="19.248376" altitud="218"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="130.62" unidades="metros"/>
            <coordenada longitud="47.581427" latitud="19.248430" altitud="214"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="476.76" unidades="metros"/>
            <coordenada longitud="47.582464" latitud="19.247612" altitud="205"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="217.97" unidades="metros"/>
            <coordenada longitud="47.586263" latitud="19.250559" altitud="214"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="55.28" unidades="metros"/>
            <coordenada longitud="47.588201" latitud="19.250122" altitud="216"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="277.76" unidades="metros"/>
            <coordenada longitud="47.588450" latitud="19.250760" altitud="219"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="43.86" unidades="metros"/>
            <coordenada longitud="47.586867" latitud="19.253625" altitud="226"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="174.73" unidades="metros"/>
            <coordenada longitud="47.586514" latitud="19.253364" altitud="226"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="126.46" unidades="metros"/>
            <coordenada longitud="47.585005" latitud="19.254014" altitud="226"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="38.92" unidades="metros"/>
            <coordenada longitud="47.584741" latitud="19.255654" altitud="227"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="6.23" unidades="metros"/>
            <coordenada longitud="47.584414" latitud="19.255839" altitud="228"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="182.65" unidades="metros"/>
            <coordenada longitud="47.584470" latitud="19.255840" altitud="228"/>
            <numeroSector>2</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="170.00" unidades="metros"/>
            <coordenada longitud="47.582837" latitud="19.255577" altitud="231"/>
            <numeroSector>3</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="35.50 " unidades="metros"/>
            <coordenada longitud="47.581498" latitud="19.256671" altitud="233"/>
            <numeroSector>3</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="388.40" unidades="metros"/>
            <coordenada longitud="47.581187" latitud="19.256564" altitud="233"/>
            <numeroSector>3</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="225.28" unidades="metros"/>
            <coordenada longitud="47.578639" latitud="19.253022" altitud="229"/>
            <numeroSector>3</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="58.25" unidades="metros"/>
            <coordenada longitud="47.579887" latitud="19.250656" altitud="226"/>
            <numeroSector>3</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="206.01" unidades="metros"/>
            <coordenada longitud="47.579471" latitud="19.250184" altitud="228"/>
            <numeroSector>3</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="97.49" unidades="metros"/>
            <coordenada longitud="47.578165" latitud="19.252132" altitud="235"/>
            <numeroSector>1</numeroSector>
        </tramo>
        
        <tramo>
            <distanciaTramo distancia="298.57" unidades="metros"/>
            <coordenada longitud="47.577496" latitud="19.251292" altitud="236"/>
            <numeroSector>1</numeroSector>
        </tramo>
    </circuito>
</circuitoInfo>
